import {
  englishMobileScreenMessages,
  hindiMobileScreenMessages,
  marathiMobileScreenMessages,
} from './mobile-screen-messages';
import {
  hindiSupplementalScreenMessages,
  marathiSupplementalScreenMessages,
} from './mobile-screen-supplemental-messages';

export type Locale = 'en' | 'hi' | 'mr';

const englishMessages = {
  ...englishMobileScreenMessages,
  account: 'Account',
  active: 'Active',
  all: 'All',
  appCitizenLabel: 'Citizen application',
  appConfigurationRequired: 'App configuration required',
  appName: 'JagrukSetu',
  authenticating: 'Authenticating',
  authEnforceDescription:
    'Use your email and password, then confirm your mobile number with a one-time SMS code.',
  authObserveDescription:
    'Use your email and password. Phone confirmation is optional in this environment.',
  authority: 'Authority',
  back: 'Back',
  browsePublicReports: 'Browse public reports',
  browsePublicReportsHint: 'Shows reviewed, privacy-protected reports',
  browseServicesHint: 'Opens all services and app destinations',
  call112: 'Call 112',
  call112Hint: 'Opens your phone app with emergency number 112',
  cancel: 'Cancel',
  categoryQuestion: 'What best describes the problem?',
  changePassword: 'Change password',
  changePasswordDescription:
    'A fresh SMS code will be sent to the confirmed phone. Saving the new password signs the account out on every device.',
  citizen: 'Citizen',
  close: 'Close',
  community: 'Community',
  complaint: 'Complaint',
  complaintDetails: 'Complaint details',
  complaintOverview: 'Complaint overview',
  complaintReceived: 'Your complaint {{number}} was received and routed.',
  complaintLinkIncomplete: 'The complaint link is incomplete.',
  confirmPassword: 'Confirm password',
  confirmedPhoneRequired: 'Confirmed phone required',
  confirmedPhoneRecoveryBody:
    'This account did not have a confirmed phone before recovery began, so the password cannot be changed here. Contact project support to restore access.',
  complaints: 'Complaints',
  complaintsNotEmergency: 'Complaints are not emergency dispatch.',
  continue: 'Continue',
  createAccount: 'Create account',
  createYourAccount: 'Create your account',
  creatingAccount: 'Creating account…',
  completingSignIn: 'Completing your secure sign-in…',
  description: 'Description',
  descriptionHint: 'Add a few words so the team knows what to look for.',
  deviceSecurity: 'Device security',
  deviceRegistered: 'This device is securely registered.',
  done: 'Done',
  email: 'Email',
  emailAddress: 'Email address',
  emergencyBody: 'For immediate danger, call 112.',
  emergencyHelp: 'Emergency help',
  english: 'English',
  evidence: 'Evidence',
  evidenceHint: 'A photo helps the right team act faster.',
  explore: 'Explore',
  forgotPassword: 'Forgot password?',
  governingBodies: 'Governing bodies',
  governingBodiesHint: 'Find municipality, ward and office coverage',
  greetingAfternoon: 'Good afternoon',
  greetingEvening: 'Good evening',
  greetingMorning: 'Good morning',
  hindi: 'हिन्दी',
  home: 'Home',
  immediateDanger: 'Immediate danger? Call 112.',
  language: 'Language',
  loadingProfile: 'Loading your profile…',
  localBody: 'Local body',
  loadMore: 'Load more',
  loaded: 'Loaded',
  loading: 'Loading…',
  loadingActivity: 'Loading your activity…',
  loadingComplaints: 'Loading your complaints…',
  loadingComplaint: 'Loading complaint…',
  loadingMore: 'Loading more complaints',
  locationQuestion: 'Where is the issue?',
  markAsRead: 'Mark as read',
  marathi: 'मराठी',
  menu: 'Menu',
  more: 'More',
  myActivity: 'My activity',
  nearbyIssues: 'Nearby issues',
  nearbyOffices: 'Nearby offices',
  nearbyReports: 'Nearby reports',
  nearbyReportsHint: 'Explore privacy-protected public reports',
  needsAttention: 'Needs attention',
  needsYou: 'Needs you',
  newReportsHere: 'New reports and updates will appear here.',
  noComplaints: 'No complaints yet',
  noComplaintsBody: 'Raise a civic issue and track every update here.',
  noComplaintsSubmitted: 'No complaints submitted yet',
  noFilteredComplaints: 'No complaints match this status',
  noNearbyIssues: 'No nearby issues yet.',
  noNotifications: 'No notifications yet',
  noNotificationsBody: 'Updates about your complaints will appear here.',
  noDescription: 'No description was stored.',
  noMessages: 'No messages yet.',
  name: 'Name',
  notifications: 'Notifications',
  notificationsHint: 'Read government messages and status alerts',
  notificationsReconnect: 'Notifications remain available after reconnect.',
  notificationAcknowledgement: 'Complaint acknowledged',
  notificationAssignment: 'Complaint assigned',
  notificationEscalation: 'Complaint escalated',
  notificationMessage: 'New private message',
  notificationReopen: 'Complaint reopened',
  notificationResolution: 'Resolution update',
  notificationStatusUpdate: 'Complaint status updated',
  notificationSubmission: 'Complaint submitted',
  notificationTransfer: 'Complaint transferred',
  officialUpdates: 'Recent official updates',
  offlineNotice:
    'You are offline. Saved reports remain on this device, but server actions need a connection.',
  openComplaints: 'Open your complaints',
  openNotifications: 'Open notifications',
  openRelatedComplaint: 'Opens the related complaint',
  openProfile: 'Open profile',
  password: 'Password',
  passwordMinimum: 'At least 8 characters',
  passwordSecurity: 'Password security',
  passwordSecurityHint:
    'Verify your registered phone with a fresh SMS code before changing your password.',
  phoneConfirmation: 'Phone confirmation',
  phoneVerification: 'Phone verification',
  optionalPhoneSetup: 'Optional phone setup',
  stepTwoOfTwo: 'Step 2 of 2',
  verifyYourPhone: 'Verify your phone',
  optionalPhoneDescription: 'Add and confirm a phone number now, or return to your profile.',
  requiredPhoneDescription:
    'Enter your mobile number. A one-time code will be sent through the configured SMS provider.',
  checkingConfirmedPhone: 'Checking your confirmed phone…',
  openAuthenticatorApp: 'Open your authenticator app',
  authenticatorInstruction:
    'No SMS is sent at this step. Enter the current rotating 6-digit code from the authenticator app that scanned this account’s earlier QR code.',
  authenticatorAfter:
    'After this code is confirmed, the mobile-number field will appear and the SMS verification code will be sent.',
  lookForFactor: 'Look for: {{label}}',
  authenticatorCode: 'Authenticator code',
  existingAuthenticatorCode: 'Existing authenticator code',
  checkingAuthenticator: 'Checking authenticator',
  confirmAuthenticator: 'Confirm authenticator',
  authenticatorRecoveryTitle: 'No longer have that authenticator?',
  authenticatorRecoveryBody:
    'A platform administrator must reset the old factor first. This security check cannot be skipped with an SMS.',
  mobileNumber: 'Mobile number',
  mobileNumberCountryCode: 'Mobile number with country code',
  phoneCountryHint:
    'Include the country code. Once confirmed, this number also authorises future password changes.',
  sendingVerificationCode: 'Sending phone verification code',
  sendVerificationCode: 'Send verification code',
  codeSentTo: 'A code was sent to {{phone}}. Enter the newest code below.',
  oneTimeCode: 'One-time code',
  phoneVerificationCode: 'Phone verification code',
  verifyingPhone: 'Verifying phone',
  verifyAndContinue: 'Verify and continue',
  sendNewCode: 'Send a new code',
  sendNewCodeIn: 'Send a new code in {{seconds}}s',
  useDifferentNumber: 'Use a different number',
  tryPhoneAgain: 'Try phone verification again',
  returnToProfile: 'Not now — return to profile',
  preferredLanguage: 'Preferred language',
  preparingReport: 'Preparing report',
  privateReport: 'Private account report',
  privateReportHint: 'Your identity and evidence are shared only with the authorised workflow.',
  privateComplaintSubmitted: 'Private complaint · submitted {{date}}',
  privateConversation: 'Private conversation',
  privateConversationHint:
    'Messages are visible only to you and currently authorised complaint staff.',
  privateMediaItems: '{{count}} private media item(s)',
  privateMessage: 'Private complaint message',
  profile: 'Profile',
  profileHint: 'Update your name and preferred language',
  profileTitle: 'Your profile',
  profileSaved: 'Your profile and language preference have been saved.',
  profileUnavailable: 'Your profile is unavailable',
  quickActions: 'Quick actions',
  raiseComplaint: 'Raise complaint',
  raiseTrackImprove: 'Raise. Track. Improve.',
  recent: 'Recent',
  read: 'Read',
  refresh: 'Refresh',
  refreshCategories: 'Refresh categories',
  registeringDevice: 'Registering this device securely…',
  report: 'Report',
  reportChoiceBody: 'Choose what to share when you review a report.',
  reportChoiceTitle: 'Your report, your choice',
  reportFiled: 'Report filed',
  reportIssue: 'Report a civic issue',
  reportNotSubmitted: 'Report not submitted',
  reportSubmitted: 'Report submitted',
  resendCode: 'Resend code',
  resolved: 'Resolved',
  restoringSession: 'Restoring your session…',
  resumeReport: 'Resume report',
  resumeSavedReport: 'Resume saved report',
  retry: 'Retry',
  retryPendingUpload: 'Retry pending upload',
  retryDeviceRegistration: 'Retry device registration',
  retryConversation: 'Retry conversation',
  returnHome: 'Return home',
  returnToSignIn: 'Return to sign in',
  returnToReport: 'Return to report',
  repeatPassword: 'Repeat your password',
  resetYourPassword: 'Reset your password',
  requestRecoveryEmail: 'Request another recovery email',
  resetPasswordDescription:
    'We first validate the secure recovery email, then send a fresh SMS code to the phone already confirmed on the account.',
  recoveryEmailHint:
    'We will email a secure recovery link without revealing whether an account exists.',
  reviewReport: 'Check your report before sending',
  routePending: 'Routing is pending verification',
  routing: 'Routing',
  routingCoverage: 'Routing coverage',
  routingUnavailable: 'Routing is not available in this environment yet.',
  save: 'Save',
  saveAndContinue: 'Save and continue',
  saveProfile: 'Save profile',
  savingProfile: 'Saving profile',
  searchPlaceholder: 'Search by issue, place, ward, or office',
  searchServices: 'Search services, reports or offices',
  sendCode: 'Send code',
  sendRecoveryEmail: 'Send recovery email',
  sendPrivateMessage: 'Send private message',
  signIn: 'Sign in',
  signInLinkRejected: 'Sign-in link not accepted',
  signedInAs: 'Signed in as {{identifier}}',
  signingIn: 'Signing in…',
  signingOut: 'Signing out',
  signOut: 'Sign out',
  statusAcknowledged: 'Acknowledged',
  statusAssigned: 'Assigned',
  statusClosed: 'Closed',
  statusHistory: 'Status history',
  statusInProgress: 'In progress',
  statusReopened: 'Reopened',
  statusResolved: 'Resolved',
  statusSubmitted: 'Submitted',
  submissionStatusUnknown: 'Submission status unknown',
  submissionUnconfirmed:
    'We could not confirm the final response. Your report may have been received. Check your complaints before submitting it again.',
  total: 'Total',
  trackStatus: 'Track status',
  tapReportToStart: 'Tap Report below to get started.',
  trustBody: 'Your report stays private. Routing is resolved from current governance data.',
  trustTitle: 'Built for accountable civic action',
  tryAgain: 'Try again',
  tryAnotherStatus: 'Try another status.',
  unableToContinue: 'Unable to continue',
  unread: 'Unread',
  verificationCode: 'Verification code',
  validatingRecovery: 'Validating your recovery link…',
  verifiedPhoneRequired:
    'A previously verified phone number is required before changing your password.',
  verifyPhoneNumber: 'Verify a phone number',
  verifyCode: 'Verify code',
  verifyPhone: 'Verify phone',
  viewAll: 'View all',
  viewComplaint: 'View complaint',
  draftSafeRetry: 'We could not submit this report. Your draft is safe to retry.',
  conversationUnavailable: 'Conversation history is temporarily unavailable.',
  messagesReadWarning: 'Messages loaded, but their read status could not be updated.',
  governmentStaff: 'Government staff',
  you: 'You',
  writePrivateMessage: 'Write a private message',
  welcomeBack: 'Welcome back',
  ward: 'Ward',
  yourName: 'Your name',
  yourComplaints: 'Your complaints',
  yourComplaintsHint: 'See receipts, progress and resolution updates',
  yourGoverningBodies: 'Your governing bodies',
  passwordChangedGlobalSignOutWarning:
    'Your password changed, but some other sessions may still be active. Sign out again before continuing.',
  passwordResetSuccess: 'Your password was reset. Sign in with your new password.',
  passwordChangedSuccess: 'Your password was changed. Sign in again on this device.',
  loadingDraft: 'Loading your draft…',
  noActiveReportBody: 'Start or resume a complaint from the home screen.',
  noActiveReportTitle: 'No active report',
  openingSubmissionResult: 'Opening your submission result…',
  officialPhoneOpenError:
    'This official phone number could not be opened. Please dial it manually.',
  discardDraftTitle: 'Discard this draft?',
  discardDraftBody: 'This permanently removes the saved report and its pending evidence.',
  keepEditing: 'Keep editing',
  discardDraft: 'Discard draft',
  officialHelpIssue: 'Official help for this issue',
  completeComplaintForm: 'Complete one complaint form',
  officialHelpFormHint: 'Use a verified official call or secure website below.',
  onePageAutosaveHint: 'Everything is on this page. Your changes save automatically.',
  offlineReportNotice: 'You are offline. Reconnect to save or submit.',
  openLocationSettings: 'Open location settings',
  updatingReport: 'Updating report…',
  issue: 'Issue',
  categoryDetails: 'Category and details',
  categoryDetailsHint: 'Choose a primary category, then the specific complaint type.',
  taxonomyUnavailable: 'The detailed complaint taxonomy is unavailable. Try again shortly.',
  checkComplaintTypes: 'Check complaint types',
  primaryCategory: 'Primary category',
  selectPrimaryCategory: 'Select a primary category',
  complaintType: 'Subcategory / issue type',
  officialHelpAvailable: 'Official help available',
  protectedIntakePending: 'Protected intake pending',
  routingSetupPending: 'Routing setup pending',
  choosePrimaryFirst: 'Choose a primary category first',
  selectSpecificIssue: 'Select the specific issue',
  routeReady: 'Route ready',
  officialHelp: 'Official help',
  routeReadyBody:
    'JagrukSetu will use your verified location to send this to the appropriate ward intake.',
  officialPrivateChannelHint: 'Use the official private channel shown below.',
  protectedIntakePreparing: 'A safe private intake is still being prepared for this issue.',
  inAppSubmissionUnavailable: 'In-app submission is not available for this issue yet.',
  officialHelpProtectedBody:
    'Choose an official channel below. JagrukSetu does not create a ward complaint, upload evidence, send an email, or publish a community post for this protected issue.',
  opensPhoneDialler: 'Opens your phone dialler',
  opensOfficialPage: 'Opens the official page inside the app',
  call: 'Call',
  open: 'Open',
  enterField: 'Enter {{field}}',
  complaintDescription: 'Complaint description',
  descriptionPlaceholder: 'Describe what you can see and why it needs attention.',
  savingSoon: 'Saving soon…',
  saving: 'Saving…',
  couldNotSave: 'Could not save',
  saved: 'Saved',
  trySavingAgain: 'Try saving again',
  issueLocation: 'Issue location',
  issueLocationHint:
    'Keep location on while you are standing near the issue. We check it automatically.',
  findingCurrentLocation: 'Finding your current location…',
  allowLocationContinue: 'Allow location to continue.',
  currentLocationNeeded: 'Current location is still needed.',
  currentLocationConfirmed: 'Current location confirmed',
  checkLocationAgain: 'Please check your location again',
  closeEnoughToSubmit: 'You are close enough to add evidence and submit.',
  moveCloser: 'Move closer to the issue and try again.',
  tryCurrentLocationAgain: 'Try current location again',
  refreshLocation: 'Refresh location',
  affectedNearbyAsset: 'Select the affected nearby asset',
  noNearbyAssets: 'No verified nearby assets found. Refresh or capture the location again.',
  distanceMetersAway: 'About {{distance}} m away',
  refreshNearbyAssets: 'Refresh nearby assets',
  photoVideoVoice: 'Photo, video or voice',
  captureEvidencePrivate: 'Capture evidence now. Originals stay private.',
  requiredEvidence: 'Required evidence',
  optionalEvidenceRequirement: 'Photo or video optional · maximum {{maximum}}',
  requiredEvidenceRequirement: '{{minimum}}–{{maximum}} finalised photo/video item(s)',
  recommended: 'Recommended: {{items}}',
  addingEvidence: 'Adding evidence…',
  retryUpload: 'Retry upload',
  voiceNote: 'Voice note',
  photo: 'Photo',
  video: 'Video',
  ready: 'Ready',
  processing: 'Processing',
  similarReports: 'Similar reports',
  similarReportsPendingHint:
    'We’ll check automatically after the required details and evidence are ready.',
  duplicateReviewHint: 'Review these before creating another report.',
  distanceSimilarity: 'About {{distance}} m away · {{similarity}}% similarity',
  duplicateAcknowledgement:
    'I reviewed these suggestions and still want to submit a separate report.',
  noSimilarReports: 'No similar nearby reports found.',
  reviewAndSubmit: 'Review and submit',
  notSelected: 'Not selected',
  notProvided: 'Not provided',
  confirmed: 'Confirmed',
  needed: 'Needed',
  evidenceReadySummary: '{{count}} photo/video ready',
  voiceAttached: 'voice note attached',
  asset: 'Asset',
  routingByWard: 'Based on your current ward',
  privateIntakeUnavailable: 'Private intake unavailable',
  notAvailableYet: 'Not available yet',
  voiceDescriptionAcknowledgement: 'I typed and reviewed the voice-note description.',
  emergencyNormalComplaintWarning:
    'Call 112 immediately if anyone is in danger. A normal complaint does not guarantee emergency response.',
  emergencyAcknowledgement: 'I understand and still want to submit a civic complaint.',
  beforeSubmit: 'Before you submit',
  serverFinalRoutingCheck: 'The server will verify routing one final time.',
  readyToSend: 'Ready to send',
  itemsLeft: '{{count}} item(s) left',
  submitComplaint: 'Submit complaint',
  statusReported: 'Reported',
  trending: 'Trending',
  heatmap: 'Heatmap',
  removeSupport: 'Remove support from {{title}}',
  support: 'Support {{title}}',
  unstar: 'Unstar {{title}}',
  star: 'Star {{title}}',
  openNamedReport: 'Open {{title}}',
  view: 'View',
  complaintDensityAreas: '{{count}} privacy-protected complaint density areas',
  reportsInGeneralizedArea: '{{count}} reports in this generalised area',
  approximateAreas: 'Approximate areas',
  yourReports: 'Your reports',
  accountView: 'Account view',
  publicReviewExplanation:
    'Submitted reports appear here immediately. They join the public feed only after privacy review.',
  youHaveNotSubmittedReport: 'You have not submitted a report yet.',
  currentAreaUnavailable: 'Your nearby area is unavailable.',
  whatsHappeningNearby: 'What’s happening nearby',
  refreshCurrentArea: 'Refresh current area',
  useCurrentArea: 'Use my current area',
  reviewedReportsAround: 'Find reviewed civic reports around you',
  allOngoing: 'All ongoing',
  apply: 'Apply',
  loadingCommunityReports: 'Loading community reports…',
  settings: 'Settings',
  loadingHeatmap: 'Loading complaint heatmap…',
  tryHeatmapAgain: 'Try heatmap again',
  trendingRegion: 'Trending across your region',
  latestNearby: 'Latest nearby',
  countLoaded: '{{count}} loaded',
  issueDensity: 'Issue density',
  privacyProtected: 'Privacy protected',
  fewer: 'Fewer',
  moreReports: 'More reports',
  noHotspots: 'No public hotspots yet',
  nothingReported: 'Nothing reported here yet',
  exactLocationsPrivate: 'Exact locations and citizen identities stay private.',
  responsibleAuthority: 'Responsible authority',
  district: 'District',
  state: 'State',
  taluka: 'Taluka',
  address: 'Address',
  officialPhone: 'Official phone',
  verifiedOn: 'Verified {{date}}',
  openOfficePhoneHint: 'Opens this verified office number in your phone dialler',
  officeEmailHint: 'Opens a new message to this verified office email',
  officeSourceHint: 'Opens the office verification source inside JagrukSetu',
  opening: 'Opening…',
  source: 'Source',
  officeActionError: 'The office {{channel}} could not be opened.',
  localAuthority: 'Local authority',
  servesLocation: 'Serves this location',
  verifiedGoverningBody: 'Verified governing body',
  officeContactsUnavailable: 'Office contacts are not published yet',
  officeContactsUnavailableBody:
    'Your civic area is verified, but no current public office contact passed the directory checks.',
  officialSourceHint: 'Opens the official verification source',
  openingOfficialSource: 'Opening official source…',
  viewCivicAreaSource: 'View civic area source',
  yourCivicArea: 'Your civic area',
  boundaryReviewNeeded: 'Boundary review needed',
  ambiguousBoundaryBody:
    'More than one verified boundary matched this location. The app will not guess which one is responsible.',
  preciseLocationNeeded: 'A more precise location is needed',
  coverageUnavailable: 'Verified coverage is not available here yet',
  precisionRequiredBody:
    'Move into an open area and try again. Accuracy must be within {{accuracy}} metres.',
  verifiedOnlyBody:
    'JagrukSetu only names a governing body when its official identity and boundary have been verified. No placeholder has been shown.',
  currentVerifiedArea: 'Current verified area',
  locationAccessNeeded: 'Location access needed',
  findingCivicArea: 'Finding your civic area',
  findingGoverningBodies: 'Finding governing bodies',
  schematicAreaAccessibility:
    'Schematic area overview. Use current location to resolve governing bodies.',
  verifiedOfficesFound: '{{count}} verified offices found',
  basedOnVerifiedArea: 'Based on your verified civic area',
  allowLocationTitle: 'Allow location to find your civic area',
  allowLocationBody: 'JagrukSetu only uses your current area to find the offices that serve it.',
  checkingAreaTitle: 'Checking your current area',
  checkingAreaBody:
    'JagrukSetu is matching your cached or current location to verified civic records.',
  chooseImageFirst: 'Choose a JPEG, PNG, or WebP image first.',
  imageSavedCleanupPending: 'Your photo was saved. An older private image is awaiting cleanup.',
  imageSaved: 'Your private profile photo was saved.',
  removePhotoTitle: 'Remove profile photo?',
  removePhotoBody: 'The private image will be permanently removed.',
  keepPhoto: 'Keep photo',
  photoRemoved: 'Your private profile photo was removed.',
  remove: 'Remove',
  profilePhoto: 'Profile photo',
  profilePhotoPrivateHint: 'Visible only to your account.',
  currentProfilePhoto: 'Current profile photo',
  citizenProfilePhoto: 'Citizen profile photo',
  imageUnavailable: 'The profile photo is temporarily unavailable.',
  imageFormats: 'JPEG, PNG or WebP · max 5 MiB',
  takePhoto: 'Take photo',
  chooseLibrary: 'Choose from library',
  uploadingPhoto: 'Uploading profile photo',
  replacePhoto: 'Replace photo',
  uploadPhoto: 'Upload photo',
  removePhoto: 'Remove photo',
  openPhotoSettings: 'Open {{source}} settings',
  currentCivicArea: 'Current civic area',
  verifiedWardHint: 'Find your verified ward and local body.',
  useCurrentLocation: 'Use my current location',
  officialSourceVerified: 'Official-source verified',
  noWardReturned: 'No ward returned',
  lastVerified: 'Last verified {{date}}',
  viewOfficialSource: 'View official source',
  noPlaceholderProfile:
    'No placeholder or unverified governing body has been added to your profile.',
  optionalEnvironment: 'Optional in this environment.',
  confirmPhoneNumber: 'Confirm a phone number',
} as const;

export type MessageKey = keyof typeof englishMessages;
export type MessageValues = Readonly<Record<string, number | string>>;
type MessageCatalog = Record<MessageKey, string>;

const hindiMessages = {
  ...hindiMobileScreenMessages,
  ...hindiSupplementalScreenMessages,
  account: 'खाता',
  active: 'सक्रिय',
  all: 'सभी',
  appCitizenLabel: 'नागरिक ऐप',
  appConfigurationRequired: 'ऐप कॉन्फ़िगरेशन आवश्यक है',
  appName: 'जागरुकसेतु',
  authenticating: 'प्रमाणीकरण हो रहा है',
  authEnforceDescription:
    'ईमेल और पासवर्ड से साइन इन करें, फिर एक बार इस्तेमाल होने वाले SMS कोड से मोबाइल नंबर की पुष्टि करें।',
  authObserveDescription:
    'ईमेल और पासवर्ड से साइन इन करें। इस वातावरण में फ़ोन पुष्टि वैकल्पिक है।',
  authority: 'प्राधिकरण',
  back: 'वापस',
  browsePublicReports: 'सार्वजनिक रिपोर्ट देखें',
  browsePublicReportsHint: 'समीक्षित, गोपनीयता-सुरक्षित रिपोर्ट दिखाता है',
  browseServicesHint: 'सभी सेवाएँ और ऐप विकल्प खोलता है',
  call112: '112 पर कॉल करें',
  call112Hint: 'आपातकालीन नंबर 112 के साथ फ़ोन ऐप खोलता है',
  cancel: 'रद्द करें',
  categoryQuestion: 'समस्या का सबसे सही वर्णन क्या है?',
  changePassword: 'पासवर्ड बदलें',
  changePasswordDescription:
    'पुष्टि किए गए फ़ोन पर नया SMS कोड भेजा जाएगा। नया पासवर्ड सहेजने पर हर डिवाइस से खाता साइन आउट हो जाएगा।',
  citizen: 'नागरिक',
  close: 'बंद करें',
  community: 'समुदाय',
  complaint: 'शिकायत',
  complaintDetails: 'शिकायत का विवरण',
  complaintOverview: 'शिकायतों का सारांश',
  complaintReceived: 'आपकी शिकायत {{number}} प्राप्त हो गई और सही विभाग को भेजी गई।',
  complaintLinkIncomplete: 'शिकायत का लिंक अधूरा है।',
  confirmPassword: 'पासवर्ड की पुष्टि करें',
  confirmedPhoneRequired: 'पुष्टि किया हुआ फ़ोन आवश्यक है',
  confirmedPhoneRecoveryBody:
    'रिकवरी शुरू होने से पहले इस खाते में पुष्टि किया फ़ोन नहीं था, इसलिए यहाँ पासवर्ड नहीं बदला जा सकता। पहुँच वापस पाने के लिए प्रोजेक्ट सहायता से संपर्क करें।',
  complaints: 'शिकायतें',
  complaintsNotEmergency: 'शिकायत सेवा आपातकालीन सहायता नहीं है।',
  continue: 'आगे बढ़ें',
  createAccount: 'खाता बनाएँ',
  createYourAccount: 'अपना खाता बनाएँ',
  creatingAccount: 'खाता बनाया जा रहा है…',
  completingSignIn: 'सुरक्षित साइन-इन पूरा हो रहा है…',
  description: 'विवरण',
  descriptionHint: 'कुछ शब्द लिखें ताकि टीम समझ सके कि क्या देखना है।',
  deviceSecurity: 'डिवाइस सुरक्षा',
  deviceRegistered: 'यह डिवाइस सुरक्षित रूप से पंजीकृत है।',
  done: 'पूर्ण',
  email: 'ईमेल',
  emailAddress: 'ईमेल पता',
  emergencyBody: 'तुरंत खतरे की स्थिति में 112 पर कॉल करें।',
  emergencyHelp: 'आपातकालीन सहायता',
  english: 'अंग्रेज़ी',
  evidence: 'साक्ष्य',
  evidenceHint: 'फ़ोटो से सही टीम को तेज़ी से कार्रवाई करने में मदद मिलती है।',
  explore: 'देखें',
  forgotPassword: 'पासवर्ड भूल गए?',
  governingBodies: 'शासकीय निकाय',
  governingBodiesHint: 'नगरपालिका, वार्ड और कार्यालय कवरेज खोजें',
  greetingAfternoon: 'नमस्कार',
  greetingEvening: 'शुभ संध्या',
  greetingMorning: 'सुप्रभात',
  hindi: 'हिन्दी',
  home: 'होम',
  immediateDanger: 'तुरंत खतरा है? 112 पर कॉल करें।',
  language: 'भाषा',
  loadingProfile: 'आपकी प्रोफ़ाइल लोड हो रही है…',
  localBody: 'स्थानीय निकाय',
  loadMore: 'और दिखाएँ',
  loaded: 'लोड हुई',
  loading: 'लोड हो रहा है…',
  loadingActivity: 'आपकी गतिविधि लोड हो रही है…',
  loadingComplaints: 'आपकी शिकायतें लोड हो रही हैं…',
  loadingComplaint: 'शिकायत लोड हो रही है…',
  loadingMore: 'और शिकायतें लोड हो रही हैं',
  locationQuestion: 'समस्या कहाँ है?',
  markAsRead: 'पढ़ा हुआ चिह्नित करें',
  marathi: 'मराठी',
  menu: 'मेन्यू',
  more: 'और',
  myActivity: 'मेरी गतिविधि',
  nearbyIssues: 'आस-पास की समस्याएँ',
  nearbyOffices: 'नज़दीकी कार्यालय',
  nearbyReports: 'आस-पास की रिपोर्ट',
  nearbyReportsHint: 'गोपनीयता-सुरक्षित सार्वजनिक रिपोर्ट देखें',
  needsAttention: 'ध्यान आवश्यक',
  needsYou: 'आपका ध्यान',
  newReportsHere: 'नई रिपोर्ट और अपडेट यहाँ दिखाई देंगे।',
  noComplaints: 'अभी कोई शिकायत नहीं',
  noComplaintsBody: 'नागरिक समस्या दर्ज करें और हर अपडेट यहाँ देखें।',
  noComplaintsSubmitted: 'अभी कोई शिकायत जमा नहीं हुई',
  noFilteredComplaints: 'इस स्थिति से मेल खाने वाली शिकायत नहीं है',
  noNearbyIssues: 'आस-पास अभी कोई समस्या नहीं है।',
  noNotifications: 'अभी कोई सूचना नहीं',
  noNotificationsBody: 'आपकी शिकायतों के अपडेट यहाँ दिखाई देंगे।',
  noDescription: 'कोई विवरण सहेजा नहीं गया।',
  noMessages: 'अभी कोई संदेश नहीं।',
  name: 'नाम',
  notifications: 'सूचनाएँ',
  notificationsHint: 'सरकारी संदेश और स्थिति अलर्ट पढ़ें',
  notificationsReconnect: 'दोबारा जुड़ने के बाद भी सूचनाएँ उपलब्ध रहेंगी।',
  notificationAcknowledgement: 'शिकायत स्वीकार की गई',
  notificationAssignment: 'शिकायत सौंपी गई',
  notificationEscalation: 'शिकायत आगे भेजी गई',
  notificationMessage: 'नया निजी संदेश',
  notificationReopen: 'शिकायत फिर खोली गई',
  notificationResolution: 'समाधान अपडेट',
  notificationStatusUpdate: 'शिकायत की स्थिति अपडेट हुई',
  notificationSubmission: 'शिकायत जमा हुई',
  notificationTransfer: 'शिकायत स्थानांतरित हुई',
  officialUpdates: 'हाल के आधिकारिक अपडेट',
  offlineNotice:
    'आप ऑफ़लाइन हैं। सहेजी गई रिपोर्ट इस डिवाइस पर रहेंगी, लेकिन सर्वर कार्यों के लिए कनेक्शन चाहिए।',
  openComplaints: 'अपनी शिकायतें खोलें',
  openNotifications: 'सूचनाएँ खोलें',
  openRelatedComplaint: 'संबंधित शिकायत खोलता है',
  openProfile: 'प्रोफ़ाइल खोलें',
  password: 'पासवर्ड',
  passwordMinimum: 'कम से कम 8 अक्षर',
  passwordSecurity: 'पासवर्ड सुरक्षा',
  passwordSecurityHint: 'पासवर्ड बदलने से पहले नए SMS कोड से अपना पंजीकृत फ़ोन सत्यापित करें।',
  phoneConfirmation: 'फ़ोन पुष्टि',
  phoneVerification: 'फ़ोन सत्यापन',
  optionalPhoneSetup: 'वैकल्पिक फ़ोन सेटअप',
  stepTwoOfTwo: 'चरण 2 में से 2',
  verifyYourPhone: 'अपना फ़ोन सत्यापित करें',
  optionalPhoneDescription: 'अभी फ़ोन नंबर जोड़कर पुष्टि करें या प्रोफ़ाइल पर लौटें।',
  requiredPhoneDescription:
    'मोबाइल नंबर दर्ज करें। कॉन्फ़िगर किए गए SMS प्रदाता से एक बार इस्तेमाल होने वाला कोड भेजा जाएगा।',
  checkingConfirmedPhone: 'पुष्टि किए गए फ़ोन की जाँच हो रही है…',
  openAuthenticatorApp: 'ऑथेंटिकेटर ऐप खोलें',
  authenticatorInstruction:
    'इस चरण में SMS नहीं भेजा जाता। उस ऑथेंटिकेटर ऐप का वर्तमान 6-अंकीय कोड दर्ज करें जिसने इस खाते का पहले वाला QR कोड स्कैन किया था।',
  authenticatorAfter:
    'इस कोड की पुष्टि के बाद मोबाइल नंबर फ़ील्ड दिखाई देगा और SMS सत्यापन कोड भेजा जाएगा।',
  lookForFactor: 'यह नाम खोजें: {{label}}',
  authenticatorCode: 'ऑथेंटिकेटर कोड',
  existingAuthenticatorCode: 'मौजूदा ऑथेंटिकेटर कोड',
  checkingAuthenticator: 'ऑथेंटिकेटर की जाँच हो रही है',
  confirmAuthenticator: 'ऑथेंटिकेटर की पुष्टि करें',
  authenticatorRecoveryTitle: 'ऑथेंटिकेटर अब उपलब्ध नहीं है?',
  authenticatorRecoveryBody:
    'पहले प्लेटफ़ॉर्म एडमिन को पुराना फ़ैक्टर रीसेट करना होगा। इस सुरक्षा जाँच को SMS से छोड़ा नहीं जा सकता।',
  mobileNumber: 'मोबाइल नंबर',
  mobileNumberCountryCode: 'देश कोड सहित मोबाइल नंबर',
  phoneCountryHint:
    'देश कोड शामिल करें। पुष्टि के बाद यही नंबर भविष्य में पासवर्ड बदलने की अनुमति भी देता है।',
  sendingVerificationCode: 'फ़ोन सत्यापन कोड भेजा जा रहा है',
  sendVerificationCode: 'सत्यापन कोड भेजें',
  codeSentTo: '{{phone}} पर कोड भेजा गया। सबसे नया कोड नीचे दर्ज करें।',
  oneTimeCode: 'एक बार इस्तेमाल होने वाला कोड',
  phoneVerificationCode: 'फ़ोन सत्यापन कोड',
  verifyingPhone: 'फ़ोन सत्यापित हो रहा है',
  verifyAndContinue: 'सत्यापित करके आगे बढ़ें',
  sendNewCode: 'नया कोड भेजें',
  sendNewCodeIn: '{{seconds}} सेकंड में नया कोड भेजें',
  useDifferentNumber: 'दूसरा नंबर इस्तेमाल करें',
  tryPhoneAgain: 'फ़ोन सत्यापन फिर करें',
  returnToProfile: 'अभी नहीं — प्रोफ़ाइल पर लौटें',
  preferredLanguage: 'पसंदीदा भाषा',
  preparingReport: 'रिपोर्ट तैयार हो रही है',
  privateReport: 'निजी खाता रिपोर्ट',
  privateReportHint: 'आपकी पहचान और साक्ष्य केवल अधिकृत प्रक्रिया के साथ साझा किए जाते हैं।',
  privateComplaintSubmitted: 'निजी शिकायत · {{date}} को जमा हुई',
  privateConversation: 'निजी बातचीत',
  privateConversationHint:
    'संदेश केवल आपको और वर्तमान अधिकृत शिकायत कर्मचारियों को दिखाई देते हैं।',
  privateMediaItems: '{{count}} निजी मीडिया सामग्री',
  privateMessage: 'निजी शिकायत संदेश',
  profile: 'प्रोफ़ाइल',
  profileHint: 'अपना नाम और पसंदीदा भाषा अपडेट करें',
  profileTitle: 'आपकी प्रोफ़ाइल',
  profileSaved: 'आपकी प्रोफ़ाइल और भाषा की पसंद सहेज दी गई है।',
  profileUnavailable: 'आपकी प्रोफ़ाइल उपलब्ध नहीं है',
  quickActions: 'त्वरित कार्य',
  raiseComplaint: 'शिकायत दर्ज करें',
  raiseTrackImprove: 'दर्ज करें। देखें। सुधारें।',
  recent: 'हाल की',
  read: 'पढ़ी गई',
  refresh: 'रीफ़्रेश करें',
  refreshCategories: 'श्रेणियाँ रीफ़्रेश करें',
  registeringDevice: 'यह डिवाइस सुरक्षित रूप से पंजीकृत हो रहा है…',
  report: 'रिपोर्ट',
  reportChoiceBody: 'रिपोर्ट की समीक्षा करते समय चुनें कि क्या साझा करना है।',
  reportChoiceTitle: 'आपकी रिपोर्ट, आपका विकल्प',
  reportFiled: 'रिपोर्ट दर्ज हो गई',
  reportIssue: 'नागरिक समस्या दर्ज करें',
  reportNotSubmitted: 'रिपोर्ट जमा नहीं हुई',
  reportSubmitted: 'रिपोर्ट जमा हो गई',
  resendCode: 'कोड फिर भेजें',
  resolved: 'समाधान हुआ',
  restoringSession: 'आपका सत्र वापस लाया जा रहा है…',
  resumeReport: 'रिपोर्ट जारी रखें',
  resumeSavedReport: 'सहेजी गई रिपोर्ट जारी रखें',
  retry: 'फिर कोशिश करें',
  retryPendingUpload: 'लंबित अपलोड फिर करें',
  retryDeviceRegistration: 'डिवाइस पंजीकरण फिर करें',
  retryConversation: 'बातचीत फिर लोड करें',
  returnHome: 'होम पर लौटें',
  returnToSignIn: 'साइन इन पर लौटें',
  returnToReport: 'रिपोर्ट पर लौटें',
  repeatPassword: 'पासवर्ड दोबारा लिखें',
  resetYourPassword: 'अपना पासवर्ड रीसेट करें',
  requestRecoveryEmail: 'दूसरा रिकवरी ईमेल माँगें',
  resetPasswordDescription:
    'पहले सुरक्षित रिकवरी ईमेल जाँचा जाएगा, फिर खाते के पुष्टि किए फ़ोन पर नया SMS कोड भेजा जाएगा।',
  recoveryEmailHint:
    'हम सुरक्षित रिकवरी लिंक ईमेल करेंगे और किसी खाते के होने या न होने का खुलासा नहीं करेंगे।',
  reviewReport: 'भेजने से पहले रिपोर्ट जाँचें',
  routePending: 'रूटिंग सत्यापन लंबित है',
  routing: 'रूटिंग',
  routingCoverage: 'रूटिंग कवरेज',
  routingUnavailable: 'इस वातावरण में रूटिंग अभी उपलब्ध नहीं है।',
  save: 'सहेजें',
  saveAndContinue: 'सहेजें और आगे बढ़ें',
  saveProfile: 'प्रोफ़ाइल सहेजें',
  savingProfile: 'प्रोफ़ाइल सहेजी जा रही है',
  searchPlaceholder: 'समस्या, स्थान, वार्ड या कार्यालय खोजें',
  searchServices: 'सेवाएँ, रिपोर्ट या कार्यालय खोजें',
  sendCode: 'कोड भेजें',
  sendRecoveryEmail: 'रिकवरी ईमेल भेजें',
  sendPrivateMessage: 'निजी संदेश भेजें',
  signIn: 'साइन इन करें',
  signInLinkRejected: 'साइन-इन लिंक स्वीकार नहीं हुआ',
  signedInAs: '{{identifier}} के रूप में साइन इन',
  signingIn: 'साइन इन हो रहा है…',
  signingOut: 'साइन आउट हो रहा है',
  signOut: 'साइन आउट',
  statusAcknowledged: 'स्वीकार की गई',
  statusAssigned: 'सौंपी गई',
  statusClosed: 'बंद',
  statusHistory: 'स्थिति इतिहास',
  statusInProgress: 'कार्य जारी',
  statusReopened: 'फिर खोली गई',
  statusResolved: 'समाधान हुआ',
  statusSubmitted: 'जमा हुई',
  submissionStatusUnknown: 'जमा होने की स्थिति स्पष्ट नहीं है',
  submissionUnconfirmed:
    'अंतिम उत्तर की पुष्टि नहीं हो सकी। आपकी रिपोर्ट प्राप्त हुई हो सकती है। दोबारा भेजने से पहले अपनी शिकायतें देखें।',
  total: 'कुल',
  trackStatus: 'स्थिति देखें',
  tapReportToStart: 'शुरू करने के लिए नीचे रिपोर्ट दबाएँ।',
  trustBody: 'आपकी रिपोर्ट निजी रहती है। वर्तमान प्रशासनिक डेटा से रूटिंग तय होती है।',
  trustTitle: 'जवाबदेह नागरिक कार्रवाई के लिए',
  tryAgain: 'फिर कोशिश करें',
  tryAnotherStatus: 'दूसरी स्थिति चुनें।',
  unableToContinue: 'आगे नहीं बढ़ सकते',
  unread: 'अपठित',
  verificationCode: 'सत्यापन कोड',
  validatingRecovery: 'रिकवरी लिंक की जाँच हो रही है…',
  verifiedPhoneRequired: 'पासवर्ड बदलने से पहले पहले से सत्यापित फ़ोन नंबर आवश्यक है।',
  verifyPhoneNumber: 'फ़ोन नंबर सत्यापित करें',
  verifyCode: 'कोड सत्यापित करें',
  verifyPhone: 'फ़ोन सत्यापित करें',
  viewAll: 'सभी देखें',
  viewComplaint: 'शिकायत देखें',
  draftSafeRetry: 'रिपोर्ट जमा नहीं हो सकी। आपका ड्राफ़्ट सुरक्षित है; फिर कोशिश करें।',
  conversationUnavailable: 'बातचीत का इतिहास अभी उपलब्ध नहीं है।',
  messagesReadWarning: 'संदेश लोड हुए, लेकिन पढ़े जाने की स्थिति अपडेट नहीं हो सकी।',
  governmentStaff: 'सरकारी कर्मचारी',
  you: 'आप',
  writePrivateMessage: 'निजी संदेश लिखें',
  welcomeBack: 'फिर से स्वागत है',
  ward: 'वार्ड',
  yourName: 'आपका नाम',
  yourComplaints: 'आपकी शिकायतें',
  yourComplaintsHint: 'रसीद, प्रगति और समाधान अपडेट देखें',
  yourGoverningBodies: 'आपके शासकीय निकाय',
} satisfies MessageCatalog;

const marathiMessages = {
  ...marathiMobileScreenMessages,
  ...marathiSupplementalScreenMessages,
  account: 'खाते',
  active: 'सक्रिय',
  all: 'सर्व',
  appCitizenLabel: 'नागरिक अॅप',
  appConfigurationRequired: 'अॅप संरचना आवश्यक आहे',
  appName: 'जागरुकसेतू',
  authenticating: 'प्रमाणीकरण होत आहे',
  authEnforceDescription:
    'ईमेल आणि पासवर्डने साइन इन करा, नंतर एकदाच वापरल्या जाणाऱ्या SMS कोडने मोबाइल क्रमांकाची पुष्टी करा.',
  authObserveDescription: 'ईमेल आणि पासवर्डने साइन इन करा. या वातावरणात फोन पुष्टीकरण ऐच्छिक आहे.',
  authority: 'प्राधिकरण',
  back: 'मागे',
  browsePublicReports: 'सार्वजनिक नोंदी पहा',
  browsePublicReportsHint: 'पुनरावलोकन केलेल्या, गोपनीयता-सुरक्षित नोंदी दाखवते',
  browseServicesHint: 'सर्व सेवा आणि अॅप पर्याय उघडते',
  call112: '112 वर कॉल करा',
  call112Hint: 'आपत्कालीन क्रमांक 112 सह फोन अॅप उघडते',
  cancel: 'रद्द करा',
  categoryQuestion: 'समस्येचे सर्वात योग्य वर्णन कोणते?',
  changePassword: 'पासवर्ड बदला',
  changePasswordDescription:
    'पुष्टी केलेल्या फोनवर नवीन SMS कोड पाठवला जाईल. नवीन पासवर्ड जतन केल्यावर खाते सर्व डिव्हाइसवरून साइन आउट होईल.',
  citizen: 'नागरिक',
  close: 'बंद करा',
  community: 'समुदाय',
  complaint: 'तक्रार',
  complaintDetails: 'तक्रारीचा तपशील',
  complaintOverview: 'तक्रारींचा आढावा',
  complaintReceived: 'तुमची तक्रार {{number}} प्राप्त झाली आणि योग्य विभागाकडे पाठवली.',
  complaintLinkIncomplete: 'तक्रारीची लिंक अपूर्ण आहे.',
  confirmPassword: 'पासवर्डची पुष्टी करा',
  confirmedPhoneRequired: 'पुष्टी केलेला फोन आवश्यक आहे',
  confirmedPhoneRecoveryBody:
    'रिकव्हरी सुरू होण्यापूर्वी या खात्यावर पुष्टी केलेला फोन नव्हता, त्यामुळे येथे पासवर्ड बदलता येणार नाही. प्रवेश परत मिळवण्यासाठी प्रकल्प सहाय्याशी संपर्क साधा.',
  complaints: 'तक्रारी',
  complaintsNotEmergency: 'तक्रार सेवा आपत्कालीन मदत नाही.',
  continue: 'पुढे',
  createAccount: 'खाते तयार करा',
  createYourAccount: 'तुमचे खाते तयार करा',
  creatingAccount: 'खाते तयार होत आहे…',
  completingSignIn: 'सुरक्षित साइन-इन पूर्ण होत आहे…',
  description: 'वर्णन',
  descriptionHint: 'पथकाला काय पाहायचे हे समजण्यासाठी थोडक्यात लिहा.',
  deviceSecurity: 'डिव्हाइस सुरक्षा',
  deviceRegistered: 'हे डिव्हाइस सुरक्षितपणे नोंदणीकृत आहे.',
  done: 'पूर्ण',
  email: 'ईमेल',
  emailAddress: 'ईमेल पत्ता',
  emergencyBody: 'तातडीचा धोका असल्यास 112 वर कॉल करा.',
  emergencyHelp: 'आपत्कालीन मदत',
  english: 'इंग्रजी',
  evidence: 'पुरावा',
  evidenceHint: 'फोटोमुळे योग्य पथकाला लवकर कारवाई करता येते.',
  explore: 'शोधा',
  forgotPassword: 'पासवर्ड विसरलात?',
  governingBodies: 'शासकीय संस्था',
  governingBodiesHint: 'महानगरपालिका, प्रभाग आणि कार्यालय शोधा',
  greetingAfternoon: 'नमस्कार',
  greetingEvening: 'शुभ संध्याकाळ',
  greetingMorning: 'शुभ प्रभात',
  hindi: 'हिन्दी',
  home: 'मुख्यपृष्ठ',
  immediateDanger: 'तातडीचा धोका आहे? 112 वर कॉल करा.',
  language: 'भाषा',
  loadingProfile: 'तुमचे प्रोफाइल लोड होत आहे…',
  localBody: 'स्थानिक संस्था',
  loadMore: 'आणखी दाखवा',
  loaded: 'लोड झाल्या',
  loading: 'लोड होत आहे…',
  loadingActivity: 'तुमची गतिविधी लोड होत आहे…',
  loadingComplaints: 'तुमच्या तक्रारी लोड होत आहेत…',
  loadingComplaint: 'तक्रार लोड होत आहे…',
  loadingMore: 'आणखी तक्रारी लोड होत आहेत',
  locationQuestion: 'समस्या कुठे आहे?',
  markAsRead: 'वाचले म्हणून चिन्हांकित करा',
  marathi: 'मराठी',
  menu: 'मेनू',
  more: 'अधिक',
  myActivity: 'माझी गतिविधी',
  nearbyIssues: 'जवळच्या समस्या',
  nearbyOffices: 'जवळची कार्यालये',
  nearbyReports: 'जवळच्या नोंदी',
  nearbyReportsHint: 'गोपनीयता-सुरक्षित सार्वजनिक नोंदी पहा',
  needsAttention: 'लक्ष आवश्यक',
  needsYou: 'तुमचे लक्ष',
  newReportsHere: 'नवीन नोंदी आणि अपडेट येथे दिसतील.',
  noComplaints: 'अजून तक्रारी नाहीत',
  noComplaintsBody: 'नागरिक समस्या नोंदवा आणि प्रत्येक अपडेट येथे पहा.',
  noComplaintsSubmitted: 'अजून तक्रार जमा झालेली नाही',
  noFilteredComplaints: 'या स्थितीशी जुळणारी तक्रार नाही',
  noNearbyIssues: 'जवळपास अजून समस्या नाहीत.',
  noNotifications: 'अजून सूचना नाहीत',
  noNotificationsBody: 'तुमच्या तक्रारींचे अपडेट येथे दिसतील.',
  noDescription: 'वर्णन जतन केलेले नाही.',
  noMessages: 'अजून संदेश नाहीत.',
  name: 'नाव',
  notifications: 'सूचना',
  notificationsHint: 'शासकीय संदेश आणि स्थिती सूचना वाचा',
  notificationsReconnect: 'पुन्हा जोडल्यावरही सूचना उपलब्ध राहतील.',
  notificationAcknowledgement: 'तक्रार स्वीकारली',
  notificationAssignment: 'तक्रार सोपवली',
  notificationEscalation: 'तक्रार पुढे पाठवली',
  notificationMessage: 'नवीन खाजगी संदेश',
  notificationReopen: 'तक्रार पुन्हा उघडली',
  notificationResolution: 'निराकरण अपडेट',
  notificationStatusUpdate: 'तक्रारीची स्थिती अपडेट झाली',
  notificationSubmission: 'तक्रार जमा झाली',
  notificationTransfer: 'तक्रार हस्तांतरित झाली',
  officialUpdates: 'अलीकडील अधिकृत अपडेट',
  offlineNotice:
    'तुम्ही ऑफलाइन आहात. जतन केलेल्या नोंदी या डिव्हाइसवर राहतील; सर्व्हर कृतींसाठी इंटरनेट आवश्यक आहे.',
  openComplaints: 'तुमच्या तक्रारी उघडा',
  openNotifications: 'सूचना उघडा',
  openRelatedComplaint: 'संबंधित तक्रार उघडते',
  openProfile: 'प्रोफाइल उघडा',
  password: 'पासवर्ड',
  passwordMinimum: 'किमान 8 अक्षरे',
  passwordSecurity: 'पासवर्ड सुरक्षा',
  passwordSecurityHint: 'पासवर्ड बदलण्यापूर्वी नवीन SMS कोडने नोंदणीकृत फोन पडताळा.',
  phoneConfirmation: 'फोन पुष्टीकरण',
  phoneVerification: 'फोन पडताळणी',
  optionalPhoneSetup: 'ऐच्छिक फोन सेटअप',
  stepTwoOfTwo: 'टप्पा 2 पैकी 2',
  verifyYourPhone: 'तुमचा फोन पडताळा',
  optionalPhoneDescription: 'आता फोन क्रमांक जोडा आणि पुष्टी करा किंवा प्रोफाइलवर परत जा.',
  requiredPhoneDescription:
    'मोबाइल क्रमांक टाका. संरचित SMS प्रदात्यामार्फत एकदाच वापरता येणारा कोड पाठवला जाईल.',
  checkingConfirmedPhone: 'पुष्टी केलेला फोन तपासला जात आहे…',
  openAuthenticatorApp: 'ऑथेंटिकेटर अॅप उघडा',
  authenticatorInstruction:
    'या टप्प्यावर SMS पाठवला जात नाही. या खात्याचा आधीचा QR कोड स्कॅन केलेल्या ऑथेंटिकेटर अॅपमधील सध्याचा 6-अंकी कोड टाका.',
  authenticatorAfter:
    'या कोडची पुष्टी झाल्यावर मोबाइल क्रमांकाचे क्षेत्र दिसेल आणि SMS पडताळणी कोड पाठवला जाईल.',
  lookForFactor: 'हे नाव शोधा: {{label}}',
  authenticatorCode: 'ऑथेंटिकेटर कोड',
  existingAuthenticatorCode: 'विद्यमान ऑथेंटिकेटर कोड',
  checkingAuthenticator: 'ऑथेंटिकेटर तपासला जात आहे',
  confirmAuthenticator: 'ऑथेंटिकेटरची पुष्टी करा',
  authenticatorRecoveryTitle: 'तो ऑथेंटिकेटर आता उपलब्ध नाही?',
  authenticatorRecoveryBody:
    'प्लॅटफॉर्म प्रशासकाने आधी जुना घटक रीसेट करणे आवश्यक आहे. ही सुरक्षा तपासणी SMS ने वगळता येत नाही.',
  mobileNumber: 'मोबाइल क्रमांक',
  mobileNumberCountryCode: 'देश कोडसह मोबाइल क्रमांक',
  phoneCountryHint:
    'देश कोड समाविष्ट करा. पुष्टी झाल्यावर हाच क्रमांक भविष्यातील पासवर्ड बदल अधिकृत करतो.',
  sendingVerificationCode: 'फोन पडताळणी कोड पाठवला जात आहे',
  sendVerificationCode: 'पडताळणी कोड पाठवा',
  codeSentTo: '{{phone}} वर कोड पाठवला. सर्वात नवीन कोड खाली टाका.',
  oneTimeCode: 'एकदाच वापरायचा कोड',
  phoneVerificationCode: 'फोन पडताळणी कोड',
  verifyingPhone: 'फोन पडताळला जात आहे',
  verifyAndContinue: 'पडताळून पुढे जा',
  sendNewCode: 'नवीन कोड पाठवा',
  sendNewCodeIn: '{{seconds}} सेकंदांत नवीन कोड पाठवा',
  useDifferentNumber: 'वेगळा क्रमांक वापरा',
  tryPhoneAgain: 'फोन पडताळणी पुन्हा करा',
  returnToProfile: 'आत्ता नको — प्रोफाइलवर परत जा',
  preferredLanguage: 'पसंतीची भाषा',
  preparingReport: 'नोंद तयार होत आहे',
  privateReport: 'खाजगी खाते नोंद',
  privateReportHint: 'तुमची ओळख आणि पुरावा फक्त अधिकृत प्रक्रियेसोबत शेअर केला जातो.',
  privateComplaintSubmitted: 'खाजगी तक्रार · {{date}} रोजी जमा',
  privateConversation: 'खाजगी संभाषण',
  privateConversationHint: 'संदेश फक्त तुम्हाला आणि सध्या अधिकृत तक्रार कर्मचाऱ्यांना दिसतात.',
  privateMediaItems: '{{count}} खाजगी मीडिया घटक',
  privateMessage: 'खाजगी तक्रार संदेश',
  profile: 'प्रोफाइल',
  profileHint: 'तुमचे नाव आणि पसंतीची भाषा अपडेट करा',
  profileTitle: 'तुमचे प्रोफाइल',
  profileSaved: 'तुमचे प्रोफाइल आणि भाषेची पसंती जतन झाली आहे.',
  profileUnavailable: 'तुमचे प्रोफाइल उपलब्ध नाही',
  quickActions: 'जलद कृती',
  raiseComplaint: 'तक्रार नोंदवा',
  raiseTrackImprove: 'नोंदवा. पाहा. सुधारणा करा.',
  recent: 'अलीकडील',
  read: 'वाचले',
  refresh: 'रीफ्रेश करा',
  refreshCategories: 'श्रेणी रीफ्रेश करा',
  registeringDevice: 'हे डिव्हाइस सुरक्षितपणे नोंदवले जात आहे…',
  report: 'नोंदवा',
  reportChoiceBody: 'नोंदीचे पुनरावलोकन करताना काय शेअर करायचे ते निवडा.',
  reportChoiceTitle: 'तुमची नोंद, तुमची निवड',
  reportFiled: 'नोंद दाखल झाली',
  reportIssue: 'नागरिक समस्या नोंदवा',
  reportNotSubmitted: 'नोंद जमा झाली नाही',
  reportSubmitted: 'नोंद जमा झाली',
  resendCode: 'कोड पुन्हा पाठवा',
  resolved: 'निराकरण झाले',
  restoringSession: 'तुमचे सत्र पुन्हा सुरू होत आहे…',
  resumeReport: 'नोंद पुढे सुरू ठेवा',
  resumeSavedReport: 'जतन केलेली नोंद पुढे सुरू ठेवा',
  retry: 'पुन्हा प्रयत्न करा',
  retryPendingUpload: 'प्रलंबित अपलोड पुन्हा करा',
  retryDeviceRegistration: 'डिव्हाइस नोंदणी पुन्हा करा',
  retryConversation: 'संभाषण पुन्हा लोड करा',
  returnHome: 'मुख्यपृष्ठावर जा',
  returnToSignIn: 'साइन इनवर परत जा',
  returnToReport: 'नोंदीकडे परत जा',
  repeatPassword: 'पासवर्ड पुन्हा लिहा',
  resetYourPassword: 'तुमचा पासवर्ड रीसेट करा',
  requestRecoveryEmail: 'दुसरा रिकव्हरी ईमेल मागवा',
  resetPasswordDescription:
    'आधी सुरक्षित रिकव्हरी ईमेल तपासला जाईल, नंतर खात्यावर पुष्टी केलेल्या फोनवर नवीन SMS कोड पाठवला जाईल.',
  recoveryEmailHint: 'खाते आहे की नाही हे उघड न करता आम्ही सुरक्षित रिकव्हरी लिंक ईमेल करू.',
  reviewReport: 'पाठवण्यापूर्वी नोंद तपासा',
  routePending: 'वाटप पडताळणी प्रलंबित आहे',
  routing: 'वाटप',
  routingCoverage: 'वाटप व्याप्ती',
  routingUnavailable: 'या वातावरणात वाटप अजून उपलब्ध नाही.',
  save: 'जतन करा',
  saveAndContinue: 'जतन करून पुढे जा',
  saveProfile: 'प्रोफाइल जतन करा',
  savingProfile: 'प्रोफाइल जतन होत आहे',
  searchPlaceholder: 'समस्या, ठिकाण, प्रभाग किंवा कार्यालय शोधा',
  searchServices: 'सेवा, नोंदी किंवा कार्यालये शोधा',
  sendCode: 'कोड पाठवा',
  sendRecoveryEmail: 'रिकव्हरी ईमेल पाठवा',
  sendPrivateMessage: 'खाजगी संदेश पाठवा',
  signIn: 'साइन इन करा',
  signInLinkRejected: 'साइन-इन लिंक स्वीकारली नाही',
  signedInAs: '{{identifier}} म्हणून साइन इन',
  signingIn: 'साइन इन होत आहे…',
  signingOut: 'साइन आउट होत आहे',
  signOut: 'साइन आउट',
  statusAcknowledged: 'स्वीकारली',
  statusAssigned: 'सोपवली',
  statusClosed: 'बंद',
  statusHistory: 'स्थिती इतिहास',
  statusInProgress: 'काम सुरू',
  statusReopened: 'पुन्हा उघडली',
  statusResolved: 'निराकरण झाले',
  statusSubmitted: 'जमा झाली',
  submissionStatusUnknown: 'जमा झाल्याची स्थिती स्पष्ट नाही',
  submissionUnconfirmed:
    'अंतिम प्रतिसादाची पुष्टी झाली नाही. तुमची नोंद प्राप्त झाली असू शकते. पुन्हा पाठवण्यापूर्वी तुमच्या तक्रारी तपासा.',
  total: 'एकूण',
  trackStatus: 'स्थिती पहा',
  tapReportToStart: 'सुरू करण्यासाठी खाली नोंदवा दाबा.',
  trustBody: 'तुमची नोंद खाजगी राहते. सध्याच्या प्रशासकीय डेटावरून वाटप ठरते.',
  trustTitle: 'उत्तरदायी नागरी कृतीसाठी',
  tryAgain: 'पुन्हा प्रयत्न करा',
  tryAnotherStatus: 'दुसरी स्थिती निवडा.',
  unableToContinue: 'पुढे जाता आले नाही',
  unread: 'न वाचलेले',
  verificationCode: 'पडताळणी कोड',
  validatingRecovery: 'रिकव्हरी लिंक तपासली जात आहे…',
  verifiedPhoneRequired: 'पासवर्ड बदलण्यापूर्वी पूर्वी पडताळलेला फोन क्रमांक आवश्यक आहे.',
  verifyPhoneNumber: 'फोन क्रमांक पडताळा',
  verifyCode: 'कोड पडताळा',
  verifyPhone: 'फोन पडताळा',
  viewAll: 'सर्व पहा',
  viewComplaint: 'तक्रार पहा',
  draftSafeRetry: 'नोंद जमा झाली नाही. तुमचा मसुदा सुरक्षित आहे; पुन्हा प्रयत्न करा.',
  conversationUnavailable: 'संभाषणाचा इतिहास सध्या उपलब्ध नाही.',
  messagesReadWarning: 'संदेश लोड झाले, पण वाचल्याची स्थिती अपडेट झाली नाही.',
  governmentStaff: 'शासकीय कर्मचारी',
  you: 'तुम्ही',
  writePrivateMessage: 'खाजगी संदेश लिहा',
  welcomeBack: 'पुन्हा स्वागत आहे',
  ward: 'प्रभाग',
  yourName: 'तुमचे नाव',
  yourComplaints: 'तुमच्या तक्रारी',
  yourComplaintsHint: 'पावत्या, प्रगती आणि निराकरण अपडेट पहा',
  yourGoverningBodies: 'तुमच्या शासकीय संस्था',
} satisfies MessageCatalog;

const messages: Readonly<Record<Locale, MessageCatalog>> = {
  en: englishMessages,
  hi: hindiMessages,
  mr: marathiMessages,
};

export function translate(locale: Locale, key: MessageKey, values?: MessageValues): string {
  const template = messages[locale][key];
  if (values === undefined) return template;
  return Object.entries(values).reduce<string>(
    (message, [name, value]) => message.replaceAll(`{{${name}}}`, String(value)),
    template,
  );
}

export function localeForIntl(locale: Locale): string {
  return locale === 'en' ? 'en-GB' : `${locale}-IN`;
}

export function getMessages(locale: Locale): Readonly<MessageCatalog> {
  return messages[locale];
}

export { messages };
