-- Generated companion for the hash-pinned canonical Phase 2 governance seed.
-- Records the externally computed main-seed SHA-256 without creating a self-reference.
-- Do not edit this file manually; run `pnpm governance:data:generate`.
begin;
do $governance_seed_checksum$
declare
  affected_rows integer;
begin
  update governance.import_batches
  set generated_seed_sha256 = 'b946eaeea4a06d16d9a53e80b0ab2e1eb6d30254ca9be0ec1232f82746a3c085'
  where id = '1340c42e-d0f0-5864-b886-5634136276a9'
    and dataset_key = 'mh_governance'
    and dataset_version = 'MH_MASTER_GOVERNANCE_DATA_v1'
    and (
      generated_seed_sha256 is null
      or generated_seed_sha256 = 'b946eaeea4a06d16d9a53e80b0ab2e1eb6d30254ca9be0ec1232f82746a3c085'
    );

  get diagnostics affected_rows = row_count;

  if affected_rows <> 1 then
    raise exception using
      errcode = '55000',
      message = 'Expected exactly one matching governance import batch while recording the generated seed checksum.';
  end if;
end
$governance_seed_checksum$;
commit;
