-- Official pilot endpoints are deliberately registered as draft and unverified.
-- An authorized reviewer must approve and schedule each endpoint after its parser,
-- expected result cardinality, and publication scope have been validated.
insert into governance.reference_sources (
  title,
  url,
  source_type,
  purpose,
  last_checked_on,
  status
)
values
  (
    'Pune Municipal Corporation official website',
    'https://www.pmc.gov.in/en',
    'official',
    'Pilot source registry root and general office contact evidence.',
    date '2026-07-14',
    'active'
  ),
  (
    'Pune Municipal Corporation officers directory',
    'https://www.pmc.gov.in/en/pmc-officers',
    'official',
    'Pilot officer and assignment discovery; an empty directory must fail validation.',
    date '2026-07-14',
    'active'
  ),
  (
    'Pune Municipal Corporation ward offices directory',
    'https://www.pmc.gov.in/en/ward-offices',
    'official',
    'Pilot ward-office and official contact discovery.',
    date '2026-07-14',
    'active'
  ),
  (
    'Pune Municipal Corporation open-data departments',
    'https://opendata.pmc.gov.in/departments',
    'official',
    'Pilot department and departmental contact discovery.',
    date '2026-07-14',
    'active'
  ),
  (
    'Brihanmumbai Municipal Corporation administrative structure',
    'https://www.mcgm.gov.in/irj/portal/anonymous/qladminis',
    'official',
    'Pilot authority hierarchy and durable officer-role discovery.',
    date '2026-07-14',
    'active'
  ),
  (
    'Brihanmumbai Municipal Corporation commissioner directory',
    'https://www.mcgm.gov.in/irj/portal/anonymous/qlmc',
    'official',
    'Pilot Municipal Commissioner assignment and official contact discovery.',
    date '2026-07-14',
    'active'
  ),
  (
    'Brihanmumbai Municipal Corporation assistant commissioners directory',
    'https://www.mcgm.gov.in/irj/portal/anonymous/qlListofAsstMC',
    'official',
    'Pilot ward Assistant Commissioner assignment and contact discovery.',
    date '2026-07-14',
    'active'
  ),
  (
    'Brihanmumbai Municipal Corporation heads of departments directory',
    'https://www.mcgm.gov.in/irj/portal/anonymous/qlListofHOD',
    'official',
    'Pilot department, role, assignment, and official contact discovery.',
    date '2026-07-14',
    'active'
  ),
  (
    'Brihanmumbai Municipal Corporation emergency contacts',
    'https://portal.mcgm.gov.in/irj/go/km/docs/documents/HomePage%20Data/List%20of%20Emergency%20Contacts.pdf',
    'official',
    'Pilot emergency authority and contact discovery.',
    date '2026-07-14',
    'active'
  ),
  (
    'Brihanmumbai Municipal Corporation contact directory',
    'https://www.mcgm.gov.in/irj/portal/anonymous/contactus',
    'official',
    'Pilot general office and official contact directory discovery.',
    date '2026-07-14',
    'active'
  )
on conflict (url) do nothing;

insert into governance.source_endpoints (
  id,
  reference_source_id,
  authority_id,
  source_key,
  source_kind,
  dataset_kind,
  retrieval_method,
  retrieval_format,
  endpoint_url,
  parser_key,
  parser_contract_version,
  expected_media_types,
  allowed_hosts,
  refresh_interval,
  status,
  verification_status,
  verification_notes,
  is_placeholder
)
values
  (
    '94100000-0000-4000-8000-000000000001',
    (select id from governance.reference_sources where url = 'https://www.pmc.gov.in/en'),
    'aa3f9456-c120-5d9b-b96e-27604b138fea',
    'pmc:official_website:office:v1',
    'official_web',
    'office',
    'http_get',
    'html',
    'https://www.pmc.gov.in/en',
    'pmc.office_directory',
    '0.1.0',
    array['text/html']::text[],
    array['www.pmc.gov.in']::text[],
    interval '1 day',
    'draft',
    'unverified',
    'Official endpoint registered only; parser layout, result cardinality, and publication scope remain under review.',
    false
  ),
  (
    '94100000-0000-4000-8000-000000000002',
    (select id from governance.reference_sources where url = 'https://www.pmc.gov.in/en/pmc-officers'),
    'aa3f9456-c120-5d9b-b96e-27604b138fea',
    'pmc:officers:assignments:v1',
    'official_web',
    'officer_assignment',
    'http_get',
    'html',
    'https://www.pmc.gov.in/en/pmc-officers',
    'pmc.officer_assignments',
    '0.1.0',
    array['text/html']::text[],
    array['www.pmc.gov.in']::text[],
    interval '1 day',
    'draft',
    'unverified',
    'Directory currently returns no records; zero results must never produce removals or automatic changes.',
    false
  ),
  (
    '94100000-0000-4000-8000-000000000003',
    (select id from governance.reference_sources where url = 'https://www.pmc.gov.in/en/ward-offices'),
    'aa3f9456-c120-5d9b-b96e-27604b138fea',
    'pmc:ward_offices:contacts:v1',
    'official_web',
    'contact',
    'http_get',
    'html',
    'https://www.pmc.gov.in/en/ward-offices',
    'pmc.ward_office_contacts',
    '0.1.0',
    array['text/html']::text[],
    array['www.pmc.gov.in']::text[],
    interval '1 day',
    'draft',
    'unverified',
    'Dynamic source requires official API discovery or a reviewed stable parser before activation.',
    false
  ),
  (
    '94100000-0000-4000-8000-000000000004',
    (select id from governance.reference_sources where url = 'https://opendata.pmc.gov.in/departments'),
    'aa3f9456-c120-5d9b-b96e-27604b138fea',
    'pmc:open_data:departments:v1',
    'official_web',
    'department',
    'http_get',
    'html',
    'https://opendata.pmc.gov.in/departments',
    'pmc.open_data_departments',
    '0.1.0',
    array['text/html']::text[],
    array['opendata.pmc.gov.in']::text[],
    interval '1 day',
    'draft',
    'unverified',
    'Dynamic department source registered for source discovery; no parser has been approved.',
    false
  ),
  (
    '94200000-0000-4000-8000-000000000001',
    (select id from governance.reference_sources where url = 'https://www.mcgm.gov.in/irj/portal/anonymous/qladminis'),
    '3fabe3b8-47cf-58fe-a59c-bb34bd02322a',
    'bmc:administration:roles:v1',
    'official_web',
    'officer_role',
    'http_get',
    'html',
    'https://www.mcgm.gov.in/irj/portal/anonymous/qladminis',
    'bmc.administrative_roles',
    '0.1.0',
    array['text/html']::text[],
    array['www.mcgm.gov.in', 'portal.mcgm.gov.in']::text[],
    interval '1 day',
    'draft',
    'unverified',
    'Official endpoint registered; extracted hierarchy must be reviewed before canonical matching.',
    false
  ),
  (
    '94200000-0000-4000-8000-000000000002',
    (select id from governance.reference_sources where url = 'https://www.mcgm.gov.in/irj/portal/anonymous/qlmc'),
    '3fabe3b8-47cf-58fe-a59c-bb34bd02322a',
    'bmc:commissioner:assignment:v1',
    'official_web',
    'officer_assignment',
    'http_get',
    'html',
    'https://www.mcgm.gov.in/irj/portal/anonymous/qlmc',
    'bmc.municipal_commissioner',
    '0.1.0',
    array['text/html']::text[],
    array['www.mcgm.gov.in', 'portal.mcgm.gov.in']::text[],
    interval '1 day',
    'draft',
    'unverified',
    'Official endpoint registered; assignment, acting-status, and contact fields require parser fixtures and review.',
    false
  ),
  (
    '94200000-0000-4000-8000-000000000003',
    (select id from governance.reference_sources where url = 'https://www.mcgm.gov.in/irj/portal/anonymous/qlListofAsstMC'),
    '3fabe3b8-47cf-58fe-a59c-bb34bd02322a',
    'bmc:assistant_commissioners:assignments:v1',
    'official_web',
    'officer_assignment',
    'http_get',
    'html',
    'https://www.mcgm.gov.in/irj/portal/anonymous/qlListofAsstMC',
    'bmc.assistant_commissioners',
    '0.1.0',
    array['text/html']::text[],
    array['www.mcgm.gov.in', 'portal.mcgm.gov.in']::text[],
    interval '1 day',
    'draft',
    'unverified',
    'Official endpoint registered; BMC lettered wards must not match numeric bootstrap placeholders.',
    false
  ),
  (
    '94200000-0000-4000-8000-000000000004',
    (select id from governance.reference_sources where url = 'https://www.mcgm.gov.in/irj/portal/anonymous/qlListofHOD'),
    '3fabe3b8-47cf-58fe-a59c-bb34bd02322a',
    'bmc:heads_of_departments:assignments:v1',
    'official_web',
    'officer_assignment',
    'http_get',
    'html',
    'https://www.mcgm.gov.in/irj/portal/anonymous/qlListofHOD',
    'bmc.department_heads',
    '0.1.0',
    array['text/html']::text[],
    array['www.mcgm.gov.in', 'portal.mcgm.gov.in']::text[],
    interval '1 day',
    'draft',
    'unverified',
    'Official endpoint registered; department and incumbent matching remain review-gated.',
    false
  ),
  (
    '94200000-0000-4000-8000-000000000005',
    (select id from governance.reference_sources where url = 'https://portal.mcgm.gov.in/irj/go/km/docs/documents/HomePage%20Data/List%20of%20Emergency%20Contacts.pdf'),
    '3fabe3b8-47cf-58fe-a59c-bb34bd02322a',
    'bmc:emergency_contacts:directory:v1',
    'official_file',
    'emergency_contact',
    'http_get',
    'pdf',
    'https://portal.mcgm.gov.in/irj/go/km/docs/documents/HomePage%20Data/List%20of%20Emergency%20Contacts.pdf',
    'bmc.emergency_contacts_pdf',
    '0.1.0',
    array['application/pdf']::text[],
    array['portal.mcgm.gov.in', 'www.mcgm.gov.in']::text[],
    interval '1 day',
    'draft',
    'unverified',
    'Official PDF registered; layout, publication date, and contact visibility require review.',
    false
  ),
  (
    '94200000-0000-4000-8000-000000000006',
    (select id from governance.reference_sources where url = 'https://www.mcgm.gov.in/irj/portal/anonymous/contactus'),
    '3fabe3b8-47cf-58fe-a59c-bb34bd02322a',
    'bmc:contact_directory:contacts:v1',
    'official_web',
    'contact',
    'http_get',
    'html',
    'https://www.mcgm.gov.in/irj/portal/anonymous/contactus',
    'bmc.contact_directory',
    '0.1.0',
    array['text/html']::text[],
    array['www.mcgm.gov.in', 'portal.mcgm.gov.in']::text[],
    interval '1 day',
    'draft',
    'unverified',
    'Official directory registered; public visibility and complaint-delivery approval remain separate reviews.',
    false
  )
on conflict (source_key) do nothing;
