-- Generated companion for the hash-pinned BMC staging/demo governance seed.
-- Records the externally computed main-seed SHA-256 without creating a self-reference.
-- Do not edit this file manually; run `pnpm governance:bmc:generate`.
begin;
do $bmc_governance_seed_checksum$
declare
  affected_rows integer;
begin
  update governance.import_batches
  set generated_seed_sha256 = '1a696300a017ad680ade3fed25a0333d3b09c6ead902cfb30ddd4b9b9074e65b'
  where id = 'ac1a5451-f0a0-5faa-91b0-2652f125969b'
    and dataset_key = 'bmc_demo_governance'
    and dataset_version = 'MUMBAI_BMC_DEMO_BOOTSTRAP_DATA_v1'
    and (
      generated_seed_sha256 is null
      or generated_seed_sha256 = '1a696300a017ad680ade3fed25a0333d3b09c6ead902cfb30ddd4b9b9074e65b'
    );

  get diagnostics affected_rows = row_count;

  if affected_rows <> 1 then
    raise exception using
      errcode = '55000',
      message = 'Expected exactly one matching BMC governance import batch while recording the generated seed checksum.';
  end if;
end
$bmc_governance_seed_checksum$;
commit;
