-- Generated by scripts/generate-bmc-demo-governance.mjs. Do not edit manually.
-- Verification companion for optional BMC internal routing seed SHA-256 9792a4dea71ffda6d46722db0ff94e49a612bd3bd1b5e4494c45e46374cf7f4c.

begin;

do $bmc_internal_routing_verification$
declare
  candidate_count integer;
  covered_case_count integer;
begin
  if (
    select count(*)
    from routing.issue_categories
    where code = any(array['garbage_dump', 'missed_sweeping', 'mosquito_breeding']::text[])
      and status = 'active'
      and verification_status = 'verified'
      and not is_placeholder
      and is_routing_eligible
  ) <> 3 then
    raise exception using errcode = '55000', message = 'BMC_ROUTING_OPERATIONAL_CATEGORY_COUNT_INVALID';
  end if;

  if (
    select count(*)
    from routing.route_rules as rule
    inner join routing.route_rule_versions as version on version.route_rule_id = rule.id
    where rule.rule_code like 'BMC_INTERNAL_%'
      and rule.status = 'active'
      and rule.verification_status = 'verified'
      and not rule.is_placeholder
      and rule.is_routing_eligible
      and version.status = 'active'
      and version.verification_status = 'verified'
      and not version.is_placeholder
      and version.is_routing_eligible
  ) <> 66 then
    raise exception using errcode = '55000', message = 'BMC_ROUTING_RULE_COUNT_INVALID';
  end if;

  with routing_cases as (
    select
      category.id as category_id,
      ward.id as ward_id,
      extensions.st_pointonsurface(boundary.boundary) as location
    from routing.issue_categories as category
    cross join governance.wards as ward
    inner join governance.ward_boundary_crosswalk_versions as crosswalk
      on crosswalk.operational_ward_id = ward.id
      and crosswalk.status = 'active'
      and crosswalk.is_routing_eligible
      and crosswalk.auto_route_allowed
      and crosswalk.relationship_type = 'one_to_one'
      and crosswalk.effective_to is null
    inner join governance.jurisdiction_boundary_versions as boundary
      on boundary.id = crosswalk.official_boundary_version_id
    where category.code = any(array['garbage_dump', 'missed_sweeping', 'mosquito_breeding']::text[])
      and ward.local_body_id = 'fa1e71b4-01e3-5e72-92e8-1476eec1adcd'
      and ward.ward_number = any(array['A', 'B', 'C', 'D', 'E', 'F/S', 'F/N', 'G/S', 'G/N', 'H/E', 'H/W', 'K/W', 'L', 'M/E', 'M/W', 'N', 'P/S', 'R/S', 'R/C', 'R/N', 'S', 'T']::text[])
  ), resolved as (
    select routing_case.category_id, routing_case.ward_id, candidate.candidate_id
    from routing_cases as routing_case
    cross join lateral public.resolve_routing_candidates(
      extensions.st_x(routing_case.location),
      extensions.st_y(routing_case.location),
      5,
      routing_case.category_id,
      null,
      '2026-07-17T00:00:00Z'::timestamptz
    ) as candidate
    where candidate.ward_id = routing_case.ward_id
  )
  select count(*), count(distinct (category_id, ward_id))
  into candidate_count, covered_case_count
  from resolved;

  if candidate_count <> 66 or covered_case_count <> 66 then
    raise exception using errcode = '55000', message = 'BMC_ROUTING_POINT_RESOLUTION_FAILED';
  end if;

  if not exists (
    select 1
    from governance.import_batches
    where dataset_key = 'bmc_demo_governance'
      and dataset_version = 'MUMBAI_BMC_DEMO_BOOTSTRAP_DATA_v1'
      and status = 'imported'
      and validation_summary ->> 'externalDeliveryApproved' = 'false'
  ) then
    raise exception using errcode = '55000', message = 'BMC_ROUTING_IMPORT_BATCH_NOT_FOUND';
  end if;
end;
$bmc_internal_routing_verification$;

commit;
